apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deployment
  labels:
    app: back
spec:
  replicas: 3
  selector:
    matchLabels:
      app: back
      tier: back
      track: daily
  template:
    metadata:
      labels:
        app: back
        tier: back
        track: daily
    spec:
      containers:
      - name: back
        image: "quanzh/zqu_back:vf"
        ports:
        - containerPort: 8080