apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  labels:
    app: front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front
      tier: front
      track: daily
  template:
    metadata:
      labels:
        app: front
        tier: front
        track: daily
    spec:
      containers:
      - name: front
        image: "quanzh/zqu_front:vf"
        ports:
        - containerPort: 8081
      resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8081
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
          - name: app.name
            valueFrom:
              configMapKeyRef:
                name: front-configmap
                key: app_name
          - name: app.back.url
            valueFrom:
              configMapKeyRef:
                name: front-configmap
                key: app_back_url