#stage1
FROM maven:3.6.3-adoptopenjdk-11 as stage1
RUN addgroup --system --gid 1001 gb && adduser --system --home /home/front --uid 1001 --gid 1001 back
RUN mkdir /app && chown -R back:gb /app
USER back
WORKDIR /app
RUN mvn clean package

#stage2
FROM openjdk:11
ENV SPRING_OUTPUT_ANSI_ENABLED=ALWAYS \
JAVA_OPTS=""
WORKDIR /app
ADD target/*.jar demo-0.0.1-SNAPSHOT.jar
EXPOSE 8080
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/app/demo-0.0.1-SNAPSHOT.jar"]
